/**
 * The fallback export: architecture as a document an agent can simply read.
 *
 * MCP is the good path, but it needs a client that speaks it and a process
 * that stays running. This is the floor — a file on disk that any agent
 * already reads, and that a human can review in a diff.
 *
 * ## Two audiences, one file
 *
 * The brief asks for human-readable *and* machine-parseable, which are usually
 * in tension. They are reconciled here by making the prose the document and
 * the machine-readable part a fenced block inside it: a person reads the
 * headings, and a parser reads the `blueprint:constraints` JSON block without
 * having to parse Markdown prose. Neither audience is served a degraded
 * version, and there is exactly one file to keep in sync.
 *
 * ## Regenerated, never merged
 *
 * The file is rewritten from scratch on every run, between explicit markers.
 * Anything outside the markers is left alone, so a developer's own notes in
 * the same file survive. Merging *inside* the block would mean reconciling a
 * stale claim with a fresh measurement, and the whole point of this tool is
 * that the measurement wins.
 */
import type { AnalysisContext } from '../server/context.js';
import { buildViolationsResponse } from '../server/violations-api.js';
import { buildIntentResponse } from '../server/intent-api.js';

export const BEGIN_MARKER = '<!-- BEGIN vibe-blueprint -->';
export const END_MARKER = '<!-- END vibe-blueprint -->';

export interface ExportMeta {
  /** ISO 8601. When this was measured. */
  readonly generatedAt: string;
  /** Commit the measurement describes, or null outside a git repository. */
  readonly commit: string | null;
}

/**
 * The machine-readable half.
 *
 * Deliberately mirrors the MCP tool payloads rather than inventing a third
 * shape: an agent that has read one should not have to learn another.
 */
function machineBlock(context: AnalysisContext, meta: ExportMeta): unknown {
  const violations = buildViolationsResponse(context);
  const intent = buildIntentResponse(context);

  return {
    tool: 'vibe-blueprint',
    generatedAt: meta.generatedAt,
    commit: meta.commit,
    modules: context.clustering.modules.map((module) => ({
      id: module.id,
      label: context.labels.labels.get(module.id)?.label ?? module.label,
      directories: module.directories,
      fileCount: module.files.length,
      provenance: 'DERIVED',
    })),
    constraints: intent.constraints.map((constraint) => ({
      id: constraint.id,
      relation: constraint.relation,
      subject: constraint.subject.phrase,
      subjectTarget: constraint.subject.target,
      object: constraint.object.phrase,
      objectTarget: constraint.object.target,
      via: constraint.via?.phrase ?? null,
      evaluable: constraint.evaluable,
      confidence: constraint.confidence,
      rawText: constraint.rawText,
      source: `${constraint.source.location}${constraint.source.line === null ? '' : `:${constraint.source.line}`}`,
      provenance: 'STATED',
    })),
    violations: violations.violations.map((violation) => ({
      id: violation.id,
      constraintId: violation.constraintId,
      kind: violation.kind,
      severity: violation.severity,
      explanation: violation.explanation,
      edges: violation.edges.map((edge) => ({
        from: edge.fromFile,
        to: edge.toFile,
        // Rule 3 survives the export, not just the API.
        evidence: edge.evidence.map((entry) => `${entry.file}:${entry.line}`),
      })),
      provenance: 'COMPARISON',
    })),
    /**
     * Carried so a reader can tell an unmeasured zero from a measured one.
     * Every other surface in this project now does; a file that omitted it
     * would be the one place the distinction was lost.
     */
    completeness: {
      documentsRead: intent.summary.documents,
      documentsFailed: intent.failures.length,
      documentsIncomplete: intent.summary.incompleteDocuments,
      modelUnavailable: intent.degraded,
      emptyReason: intent.emptyReason,
      uncheckableStatements: intent.summary.uncheckable,
    },
  };
}

export function renderAgentsMarkdown(context: AnalysisContext, meta: ExportMeta): string {
  const violations = buildViolationsResponse(context);
  const intent = buildIntentResponse(context);
  const lines: string[] = [];

  lines.push(BEGIN_MARKER);
  lines.push('');
  lines.push('## Architecture (measured)');
  lines.push('');
  lines.push(
    `Generated by vibe-blueprint at ${meta.generatedAt}` +
      `${meta.commit === null ? '' : ` from commit \`${meta.commit}\``}. ` +
      'Regenerated on every run — edit the source documents, not this block.',
  );
  lines.push('');
  lines.push(
    'Everything under **Derived** is traced to a real import statement. Everything under ' +
      '**Stated** is a claim someone wrote in prose and may be stale or wrong. They are never merged.',
  );
  lines.push('');

  // ---- derived
  lines.push('### Derived structure');
  lines.push('');
  lines.push(
    `${context.clustering.modules.length} module(s) over ${context.graph.graph.order} file(s) ` +
      `and ${context.graph.graph.size} import edge(s).`,
  );
  lines.push('');
  lines.push('| Module | Files | Directories |');
  lines.push('| --- | ---: | --- |');
  for (const module of context.clustering.modules) {
    const label = context.labels.labels.get(module.id)?.label ?? module.label;
    lines.push(`| ${label} (\`${module.id}\`) | ${module.files.length} | ${module.directories.join(', ')} |`);
  }
  lines.push('');

  // ---- stated
  lines.push('### Stated rules');
  lines.push('');
  if (intent.constraints.length === 0) {
    lines.push(emptyConstraintNote(intent.emptyReason));
  } else {
    for (const constraint of intent.constraints) {
      const where = `${constraint.source.location}${constraint.source.line === null ? '' : `:${constraint.source.line}`}`;
      lines.push(
        `- **${constraint.relation}** — ${constraint.subject.phrase} → ${constraint.object.phrase}` +
          `${constraint.via === null ? '' : ` (via ${constraint.via.phrase})`}` +
          `${constraint.evaluable ? '' : ' _(could not be checked)_'}`,
      );
      lines.push(`  > ${constraint.rawText.replace(/\s+/g, ' ').trim()}`);
      lines.push(`  _${where}_`);
    }
  }
  lines.push('');

  if (intent.summary.uncheckable > 0) {
    lines.push(
      `${intent.summary.uncheckable} further architectural statement(s) were found that no import ` +
        'graph can decide (style preferences, process rules, runtime behaviour). They are counted, not enforced.',
    );
    lines.push('');
  }

  // ---- comparison
  lines.push('### Where they disagree');
  lines.push('');
  if (violations.violations.length === 0) {
    lines.push(emptyViolationNote(violations.emptyReason));
  } else {
    for (const violation of violations.violations) {
      lines.push(`- **[${violation.severity}]** ${violation.explanation}`);
      lines.push(`  > ${violation.constraint.rawText.replace(/\s+/g, ' ').trim()}`);
      for (const edge of violation.edges.slice(0, 3)) {
        const first = edge.evidence[0];
        if (first !== undefined) lines.push(`  - \`${first.file}:${first.line}\` — ${first.snippet.trim()}`);
      }
    }
  }
  lines.push('');

  lines.push('### Machine-readable');
  lines.push('');
  lines.push('```json blueprint:constraints');
  lines.push(JSON.stringify(machineBlock(context, meta), null, 2));
  lines.push('```');
  lines.push('');
  lines.push(END_MARKER);

  return lines.join('\n');
}

function emptyConstraintNote(reason: ReturnType<typeof buildIntentResponse>['emptyReason']): string {
  switch (reason) {
    case 'no-documents':
      return 'No README, AGENTS.md, CLAUDE.md or ADRs were found, so there was nothing to read.';
    case 'not-attempted':
      return 'Documents were found but not read: reading prose needs a model and none was available. This is "not attempted", not "nothing stated".';
    case 'extraction-failed':
      return 'Some documents could not be read to the end, so this list is incomplete. A rule may exist that is simply missing here.';
    case 'nothing-stated':
      return 'The documents were read and stated no dependency rule that can be checked against an import graph.';
    default:
      return 'No stated rules.';
  }
}

function emptyViolationNote(reason: ReturnType<typeof buildViolationsResponse>['emptyReason']): string {
  switch (reason) {
    case 'no-constraints':
      return 'Nothing to compare: no checkable rule was stated. This is "not measured", not "clean".';
    case 'all-unchecked':
      return 'Rules were stated but none could be evaluated against the graph, so nothing was measured.';
    case 'all-satisfied':
      return 'Every stated rule was checked against the graph and holds.';
    default:
      return 'No disagreements found.';
  }
}

/**
 * Splices the generated block into an existing file, replacing only what lies
 * between the markers. A file that has never been exported to gets the block
 * appended; anything the developer wrote around it is preserved verbatim.
 */
export function spliceIntoDocument(existing: string, block: string): string {
  const begin = existing.indexOf(BEGIN_MARKER);
  const end = existing.indexOf(END_MARKER);

  if (begin === -1 || end === -1 || end < begin) {
    const separator = existing.trim() === '' ? '' : `${existing.replace(/\s+$/, '')}\n\n`;
    return `${separator}${block}\n`;
  }

  const before = existing.slice(0, begin);
  const after = existing.slice(end + END_MARKER.length);
  return `${before}${block}${after}`;
}
