/**
 * The Student Project Pack: documents added to a downloaded project so a
 * person can understand it, present it, defend it in a viva, and host it for
 * free - written from the project's own plan and code, never invented.
 *
 *   docs/PROJECT-REPORT.md  a report in the usual college structure, facts filled in
 *   docs/ARCHITECTURE.md    how a request travels through this project, for learners
 *   docs/API.md             every endpoint, with a command to try it
 *   docs/VIVA-PREP.md       questions an examiner may ask about this project
 *   docs/DEPLOY-FREE.md     putting it online on free plans
 *
 * Deterministic: the same project always produces the same documents, and a
 * sentence states only what the plan (ProjectSchema), the files
 * (project-facts.ts) or the verification result says. What only the author
 * can know - scope, analysis, conclusion - is left as marked prompts to write
 * in their own words; the report says so at the top, because a report handed
 * in as the student's own work has to be.
 *
 * Added at download time only, like runnable-project.ts, and never over a
 * file the project already has.
 */
import { DOMAIN_NAMES, type DomainName, type ProjectSchema } from '../types/project-schema.js';
import { componentTargetPath } from '../generate/assemble.js';
import { extractEndpoints, extractTables, type Endpoint, type Table } from './project-facts.js';
import type { ZipEntry } from './runnable-project.js';

export interface PackVerification {
  readonly buildOk: boolean;
  /** Blueprint architecture violations still unresolved after repair. */
  readonly architectureViolations: number;
  /** Suspected security-check evasions still unresolved. */
  readonly securityFindings: number;
  readonly repairRounds: number;
}

export interface ProjectPackInput {
  readonly schema: ProjectSchema;
  readonly verification?: PackVerification;
}

interface Module {
  readonly domain: DomainName;
  readonly name: string;
  readonly purpose: string;
  /** Null when the planned file is not in the project (a hand-edited or partial run). */
  readonly file: string | null;
}

interface PackFacts {
  readonly title: string;
  readonly prompt: string;
  readonly modules: readonly Module[];
  readonly dependsOn: Readonly<Record<DomainName, readonly DomainName[]>>;
  readonly endpoints: readonly Endpoint[];
  readonly tables: readonly Table[];
  readonly stack: readonly (readonly [string, string])[];
  readonly verification?: PackVerification;
}

const LAYER: Readonly<Record<DomainName, string>> = {
  frontend: 'Frontend (pages the user sees)',
  backend: 'Backend (API routes)',
  database: 'Database (tables and queries)',
  security: 'Security (middleware)',
};

export const README_MARKER = 'Generated by Vibe-Code Blueprint.';

export function withProjectPack(entries: readonly ZipEntry[], input: ProjectPackInput): readonly ZipEntry[] {
  const facts = gatherFacts(entries, input);
  const documents: ZipEntry[] = [
    { path: 'docs/PROJECT-REPORT.md', contents: projectReport(facts) },
    { path: 'docs/ARCHITECTURE.md', contents: architectureGuide(facts) },
    { path: 'docs/API.md', contents: apiReference(facts) },
    { path: 'docs/VIVA-PREP.md', contents: vivaPrep(facts) },
    { path: 'docs/DEPLOY-FREE.md', contents: deployFree(facts) },
  ];
  const paths = new Set(entries.map((entry) => entry.path));
  const added = documents.filter((document) => !paths.has(document.path));
  const withLinks = entries.map((entry) =>
    entry.path === 'README.md' && entry.contents.includes(README_MARKER) ? { ...entry, contents: readmeWithDocs(entry.contents, added) } : entry,
  );
  return [...withLinks, ...added];
}

function gatherFacts(entries: readonly ZipEntry[], input: ProjectPackInput): PackFacts {
  const { schema } = input;
  const paths = new Set(entries.map((entry) => entry.path));
  const modules = DOMAIN_NAMES.flatMap((domain) =>
    schema.domains[domain].components.map((component) => {
      const file = componentTargetPath(domain, component);
      return { domain, name: component.name, purpose: component.purpose, file: paths.has(file) ? file : null };
    }),
  );
  const dependsOn = Object.fromEntries(DOMAIN_NAMES.map((domain) => [domain, schema.domains[domain].dependsOn])) as Record<
    DomainName,
    readonly DomainName[]
  >;
  return {
    title: schema.title,
    prompt: schema.originalPrompt.trim(),
    modules,
    dependsOn,
    endpoints: extractEndpoints(entries),
    tables: extractTables(entries),
    stack: techStack(entries),
    ...(input.verification === undefined ? {} : { verification: input.verification }),
  };
}

/** Only what the project really uses: its package.json and its imports. */
function techStack(entries: readonly ZipEntry[]): readonly (readonly [string, string])[] {
  const manifest = entries.find((entry) => entry.path === 'package.json')?.contents ?? '';
  const uses = (name: string): boolean => manifest.includes(`"${name}"`);
  const sqlite = entries.some((entry) => entry.contents.includes("'node:sqlite'") || entry.contents.includes('"node:sqlite"'));
  const stack: [string, string][] = [['Language', 'TypeScript (strict)']];
  if (entries.some((entry) => entry.path.startsWith('frontend/'))) stack.push(['Frontend', `React${uses('vite') ? ' with Vite' : ''}`]);
  if (uses('express')) stack.push(['Backend', 'Node.js with Express']);
  if (sqlite) stack.push(['Database', 'SQLite (built into Node.js 22.5+, node:sqlite)']);
  stack.push(['Architecture checks', 'Vibe-Code Blueprint (import rules verified on every build)']);
  return stack;
}

// ---- small shared helpers ---------------------------------------------------

const cell = (text: string): string => text.replace(/\|/g, '\\|').replace(/\s*\n\s*/g, ' ');
/** The prompt quoted mid-sentence: one line, without its own closing full stop. */
const inSentence = (text: string): string => text.replace(/\s*\n\s*/g, ' ').replace(/[.!\s]+$/, '');
const code = (text: string): string => `\`${text}\``;
const safeId = (text: string): string => text.replace(/[^A-Za-z0-9_]/g, '_');

function table(head: readonly string[], rows: readonly (readonly string[])[]): string[] {
  return [`| ${head.join(' | ')} |`, `|${head.map(() => '---').join('|')}|`, ...rows.map((row) => `| ${row.map(cell).join(' | ')} |`)];
}

function modulesOf(facts: PackFacts, domain: DomainName): readonly Module[] {
  return facts.modules.filter((module) => module.domain === domain);
}

function count(n: number, one: string, many = `${one}s`): string {
  return `${n} ${n === 1 ? one : many}`;
}

/** Which layers each layer may use and must not use - the rules the Blueprint check enforces. */
function layerRules(facts: PackFacts): { readonly domain: DomainName; readonly may: readonly DomainName[]; readonly mustNot: readonly DomainName[] }[] {
  return DOMAIN_NAMES.map((domain) => ({
    domain,
    may: facts.dependsOn[domain],
    mustNot: DOMAIN_NAMES.filter((other) => other !== domain && !facts.dependsOn[domain].includes(other)),
  }));
}

function layerDiagram(facts: PackFacts): string[] {
  const lines = ['```mermaid', 'flowchart TD'];
  for (const domain of DOMAIN_NAMES) lines.push(`  ${domain}["${LAYER[domain]}<br/>${count(modulesOf(facts, domain).length, 'module')}"]`);
  for (const domain of DOMAIN_NAMES) for (const target of facts.dependsOn[domain]) lines.push(`  ${domain} --> ${target}`);
  lines.push('```');
  return lines;
}

function erDiagram(tables: readonly Table[]): string[] {
  const lines = ['```mermaid', 'erDiagram'];
  for (const entry of tables) {
    lines.push(`  ${safeId(entry.name)} {`);
    for (const column of entry.columns) lines.push(`    ${column.type || 'VALUE'} ${safeId(column.name)}${column.primaryKey ? ' PK' : ''}`);
    lines.push('  }');
  }
  for (const entry of tables) {
    for (const reference of entry.references) lines.push(`  ${safeId(entry.name)} }o--|| ${safeId(reference.table)} : "${reference.column}"`);
  }
  lines.push('```');
  return lines;
}

function verificationLines(verification: PackVerification | undefined): string[] {
  if (verification === undefined) return ['_No verification result was recorded for this download._'];
  const mark = (ok: boolean): string => (ok ? 'Passed' : 'Needs attention');
  return table(
    ['Check', 'Result'],
    [
      ['TypeScript build of the whole project', mark(verification.buildOk)],
      ['Architecture rules (Blueprint import check)', verification.architectureViolations === 0 ? 'Passed - no violations' : `${count(verification.architectureViolations, 'violation')} to review`],
      ['Security check (no bypass of the security middleware)', verification.securityFindings === 0 ? 'Passed' : `${count(verification.securityFindings, 'finding')} to review`],
      ['Automatic repair rounds used', String(verification.repairRounds)],
    ],
  );
}

// ---- docs/PROJECT-REPORT.md -------------------------------------------------

function projectReport(facts: PackFacts): string {
  return [
    `# ${facts.title} - Project Report`,
    '',
    '> Drafted automatically from this project\'s plan and code by Vibe-Code Blueprint: every fact below comes from the',
    '> project\'s own files. Read it, correct it, and write the sections marked ✍️ in your own words. If your',
    '> institution asks, state which parts were drafted with an AI tool.',
    '',
    ...reportAbstract(facts),
    ...reportIntroduction(facts),
    ...reportArchitecture(facts),
    ...reportData(facts),
    ...reportImplementation(facts),
    ...reportTesting(facts),
    '## 8. Conclusion and future scope ✍️',
    '',
    '_What did the project achieve against its objectives? What would you add next (for example: user accounts, persistent hosting, more tests)?_',
    '',
    '## References',
    '',
    '1. React documentation - https://react.dev',
    '2. Express documentation - https://expressjs.com',
    '3. Node.js SQLite module - https://nodejs.org/api/sqlite.html',
    '4. TypeScript handbook - https://www.typescriptlang.org/docs/',
    '5. Vite guide - https://vite.dev/guide/',
    '',
  ].join('\n');
}

function reportAbstract(facts: PackFacts): string[] {
  const counts = DOMAIN_NAMES.map((domain) => `${count(modulesOf(facts, domain).length, 'module')} in the ${domain} layer`).join(', ');
  const checked =
    facts.verification === undefined
      ? ''
      : facts.verification.buildOk
        ? ' The complete project builds, and its architecture rules are checked automatically on every build.'
        : ' The project does not build cleanly yet (see section 6); its architecture rules are checked automatically on every build.';
  return [
    '## Abstract',
    '',
    `${facts.title} is a web application built from the brief "${inSentence(facts.prompt)}". It is organised in four layers - ${counts} - ` +
      `exposing ${count(facts.endpoints.length, 'API endpoint')} and storing data in ${count(facts.tables.length, 'database table')}.${checked}`,
    '',
  ];
}

function reportIntroduction(facts: PackFacts): string[] {
  return [
    '## 1. Introduction',
    '',
    '### 1.1 Problem statement',
    '',
    `> ${facts.prompt.replace(/\n+/g, ' ')}`,
    '',
    '### 1.2 Objectives',
    '',
    ...facts.modules.map((module) => `- **${module.name}** - ${module.purpose}`),
    '',
    '### 1.3 Scope ✍️',
    '',
    '_Who will use the system, and what is deliberately left out?_',
    '',
  ];
}

function reportArchitecture(facts: PackFacts): string[] {
  const rules = layerRules(facts).map((rule) => [LAYER[rule.domain], rule.may.join(', ') || '-', rule.mustNot.join(', ') || '-']);
  const modules = facts.modules.map((module) => [module.domain, module.name, module.purpose, module.file === null ? '-' : code(module.file)]);
  return [
    '## 2. System architecture',
    '',
    'The application follows a layered architecture: each layer has one job and may only use the layers below it. The arrows',
    'show which layer may use which.',
    '',
    ...layerDiagram(facts),
    '',
    '### 2.1 Architecture rules',
    '',
    'These rules are not only documentation: every build checks the real imports in the code against them (see section 6).',
    '',
    ...table(['Layer', 'May use', 'Must not use'], rules),
    '',
    '### 2.2 Modules',
    '',
    ...table(['Layer', 'Module', 'Purpose', 'File'], modules),
    '',
  ];
}

function reportData(facts: PackFacts): string[] {
  const lines = ['## 3. Database design', ''];
  if (facts.tables.length === 0) {
    lines.push('_No `CREATE TABLE` statement was found in the code, so no tables are listed._', '');
  } else {
    lines.push(...erDiagram(facts.tables), '');
    for (const entry of facts.tables) {
      lines.push(`### Table ${code(entry.name)} (${code(entry.file)})`, '');
      lines.push(...table(['Column', 'Type', 'Key', 'Required'], entry.columns.map((c) => [c.name, c.type || '-', c.primaryKey ? 'Primary key' : '', c.notNull ? 'Yes' : ''])), '');
    }
  }
  lines.push('## 4. API design', '');
  if (facts.endpoints.length === 0) lines.push('_No mounted API routes were found._', '');
  else lines.push(...table(['Method', 'Endpoint', 'Defined in'], facts.endpoints.map((e) => [e.method, code(e.path), code(e.file)])), '', 'Examples for each endpoint are in `docs/API.md`.', '');
  return lines;
}

function reportImplementation(facts: PackFacts): string[] {
  return ['## 5. Implementation', '', ...table(['Part', 'Technology'], facts.stack), '', 'How to run it is in `README.md`.', ''];
}

function reportTesting(facts: PackFacts): string[] {
  const cases = facts.endpoints.slice(0, 8).map((endpoint) => [`${endpoint.method} ${endpoint.path}`, 'Call it with valid input (see docs/API.md)', 'A successful response', '✍️']);
  return [
    '## 6. Testing and verification',
    '',
    '### 6.1 Automatic checks',
    '',
    ...verificationLines(facts.verification),
    '',
    '### 6.2 Manual test cases ✍️',
    '',
    '_Run each case, then fill in the result column._',
    '',
    ...table(['Test case', 'Steps', 'Expected', 'Result'], cases.length > 0 ? cases : [['Open the home page', 'npm run web, open the link', 'The page loads', '✍️']]),
    '',
    '## 7. Results ✍️',
    '',
    '_Add screenshots of each page and describe what they show._',
    '',
  ];
}

// ---- docs/ARCHITECTURE.md ---------------------------------------------------

function architectureGuide(facts: PackFacts): string {
  const example = facts.endpoints[0];
  const table0 = facts.tables[0];
  const security = modulesOf(facts, 'security');
  const lines = [
    `# How ${facts.title} works`,
    '',
    'A guide for anyone learning from this project: what each part does, and the path one request takes through it.',
    '',
    '## The layers',
    '',
    ...DOMAIN_NAMES.flatMap((domain) => [
      `### ${LAYER[domain]}`,
      '',
      ...(modulesOf(facts, domain).length === 0 ? ['_None in this project._'] : modulesOf(facts, domain).map((m) => `- **${m.name}**${m.file === null ? '' : ` (${code(m.file)})`} - ${m.purpose}`)),
      '',
    ]),
    '## One request, end to end',
    '',
    '```mermaid',
    'sequenceDiagram',
    '  participant U as User',
    '  participant F as Frontend page',
    ...(security.length > 0 ? ['  participant S as Security middleware'] : []),
    '  participant B as Backend route',
    '  participant D as Database',
    '  U->>F: clicks or submits a form',
    `  F->>${security.length > 0 ? 'S' : 'B'}: ${example === undefined ? 'HTTP request to /api/...' : `${example.method} ${example.path}`}`,
    ...(security.length > 0 ? ['  S->>B: request allowed'] : []),
    `  B->>D: ${table0 === undefined ? 'reads or writes data' : `reads or writes ${table0.name}`}`,
    '  D-->>B: rows',
    '  B-->>F: JSON response',
    '  F-->>U: updated page',
    '```',
    '',
    '## Why the rules matter',
    '',
    ...(facts.dependsOn.frontend.includes('database')
      ? []
      : [
          '- **The frontend never touches the database directly.** Every read and write goes through the API, so the backend\'s',
          '  checks run on every request, and the UI can change without breaking the data.',
        ]),
    '- **Each layer only uses the layers it is allowed to.** That keeps each part replaceable and testable on its own.',
    '- **The rules are checked, not just written down.** Vibe-Code Blueprint reads every import in the code and flags one that',
    '  breaks a rule, with the file and line.',
    '',
  ];
  return lines.join('\n');
}

// ---- docs/API.md ------------------------------------------------------------

function apiReference(facts: PackFacts): string {
  const lines = [`# ${facts.title} - API`, '', 'Start the backend first (`npm run build`, then `npm start`); it listens on http://localhost:3000.', ''];
  if (facts.endpoints.length === 0) return [...lines, '_No mounted API routes were found in `backend/src/index.ts`._', ''].join('\n');
  for (const endpoint of facts.endpoints) {
    const body = endpoint.method === 'GET' || endpoint.method === 'DELETE' ? '' : " -H 'content-type: application/json' -d '{}'";
    lines.push(`## ${endpoint.method} ${code(endpoint.path)}`, '', `Defined in ${code(endpoint.file)}.`, '', '```bash', `curl -X ${endpoint.method} http://localhost:3000${endpoint.path}${body}`, '```', '');
  }
  lines.push('_Replace `{}` with the fields the route expects - open the file named above to see them._', '');
  return lines.join('\n');
}

// ---- docs/VIVA-PREP.md ------------------------------------------------------

function vivaPrep(facts: PackFacts): string {
  const qa = (question: string, hint: string): string[] => [`**Q. ${question}**`, '', `_Hint:_ ${hint}`, ''];
  const lines = [`# ${facts.title} - Viva preparation`, '', 'Questions an examiner may ask about this project, with where to find the answer. Answer in your own words.', ''];
  lines.push('## About the project', '', ...qa('What problem does this project solve, and for whom?', `The brief was "${inSentence(facts.prompt)}".`));
  lines.push(...qa('Why is the application split into frontend, backend, database and security layers?', 'Separation of concerns: see docs/ARCHITECTURE.md, "Why the rules matter".'));
  lines.push('## Architecture', '');
  for (const rule of layerRules(facts)) {
    if (rule.mustNot.length === 0) continue;
    const allowed = rule.may.length === 0 ? 'It uses no other layer' : `It may use only ${rule.may.join(', ')}`;
    lines.push(...qa(`Why may the ${rule.domain} layer not use ${rule.mustNot.join(' or ')}?`, `${allowed}; the build checks this on every import (report section 2.1).`));
  }
  lines.push('## Modules', '');
  for (const module of facts.modules) lines.push(...qa(`What does ${module.name} do, and where is it implemented?`, `${module.purpose}${module.file === null ? '' : ` - ${code(module.file)}`}.`));
  if (facts.endpoints.length > 0) lines.push('## API', '');
  for (const endpoint of facts.endpoints.slice(0, 8)) lines.push(...qa(`What happens when a client calls ${endpoint.method} ${endpoint.path}?`, `Follow ${code(endpoint.file)}; docs/ARCHITECTURE.md shows the path of one request.`));
  if (facts.tables.length > 0) lines.push('## Database', '');
  for (const entry of facts.tables) {
    const keys = entry.columns.filter((column) => column.primaryKey).map((column) => column.name);
    lines.push(...qa(`Explain the ${entry.name} table. What is its primary key?`, `Columns: ${entry.columns.map((c) => c.name).join(', ')}. Primary key: ${keys.join(', ') || 'none declared'}.`));
  }
  lines.push('## Testing', '', ...qa('How did you verify that the project works?', 'Report section 6: the automatic build and architecture checks, plus your manual test cases.'));
  return lines.join('\n');
}

// ---- docs/DEPLOY-FREE.md ----------------------------------------------------

function deployFree(facts: PackFacts): string {
  const hasApi = facts.endpoints.length > 0;
  return [
    `# Putting ${facts.title} online for free`,
    '',
    'Free plans change; check each provider\'s current limits before relying on one.',
    '',
    '## 1. Put the code on GitHub',
    '',
    'Create a free repository and push this folder. Students can also claim the GitHub Student Developer Pack',
    '(education.github.com/pack), which adds free credits and tools from many providers.',
    '',
    '## 2. The web UI (static hosting)',
    '',
    'Build it with `npm run web:build`; the site is in `dist/web`. Any free static host serves it: GitHub Pages,',
    'Netlify, Vercel or Cloudflare Pages.',
    '',
    ...(hasApi
      ? [
          '## 3. The API (a small Node.js service)',
          '',
          'Host the backend on a free web-service plan (for example Render or Koyeb):',
          '',
          '- Build command: `npm install && npm run build`',
          '- Start command: `npm start`',
          '',
          'Free services usually sleep when idle, so the first request after a pause is slow. The database here is SQLite in',
          'the service itself: data does not survive a restart on most free plans, which is fine for a demo but not for real users.',
          '',
          '## 4. Connect the two',
          '',
          'The UI calls the API at `/api/...` on its own domain. Forward those calls to your API service with a rewrite rule:',
          '',
          '- Netlify - a file `dist/web/_redirects` containing: `/api/*  https://YOUR-API-HOST/api/:splat  200`',
          '- Vercel - `vercel.json`: `{ "rewrites": [{ "source": "/api/:path*", "destination": "https://YOUR-API-HOST/api/:path*" }] }`',
          '',
        ]
      : []),
  ].join('\n');
}

function readmeWithDocs(readme: string, added: readonly ZipEntry[]): string {
  if (added.length === 0) return readme;
  const titles: Readonly<Record<string, string>> = {
    'docs/PROJECT-REPORT.md': 'Project report (college format, facts filled in)',
    'docs/ARCHITECTURE.md': 'How it works - for learners',
    'docs/API.md': 'API reference with example commands',
    'docs/VIVA-PREP.md': 'Viva preparation questions',
    'docs/DEPLOY-FREE.md': 'Put it online for free',
  };
  const links = added.map((document) => `- [${titles[document.path] ?? document.path}](${document.path})`);
  return `${readme.trimEnd()}\n\n## Project documents\n\n${links.join('\n')}\n`;
}
