/**
 * Makes a downloaded project runnable, not only buildable.
 *
 * The generated project is verified with ONE `tsc` over backend and frontend
 * (assemble.ts): that proves the frontend compiles, but a browser cannot load
 * `.tsx` - there was no `index.html`, no bundler and no script to start one,
 * so an unzipped project's UI could not be opened at all (found live,
 * 2026-09-27).
 *
 * Added at download time only, never to the project the pipeline builds and
 * verifies: the verified build stays exactly what it was (and code-model
 * capture is unaffected), while the zip gains the few files a person needs:
 *
 *   - `frontend/index.html` with the `#root` that `frontend/src/main.tsx` mounts into;
 *   - `vite.config.mjs`, serving `frontend/` and proxying `/api` to the backend on :3000;
 *   - `web` / `web:build` scripts and the two Vite dev dependencies in `package.json`;
 *   - a README with the exact commands.
 *
 * A file the project already has is never overwritten.
 */
export interface ZipEntry {
  readonly path: string;
  readonly contents: string;
}

export const FRONTEND_ENTRY = 'frontend/src/main.tsx';
export const VITE_VERSION = '^5.4.10';
export const VITE_REACT_PLUGIN_VERSION = '^4.3.3';

export function withRunScaffold(entries: readonly ZipEntry[], title = 'Generated app'): readonly ZipEntry[] {
  const paths = new Set(entries.map((entry) => entry.path));
  const hasFrontend = paths.has(FRONTEND_ENTRY);
  const hasBackend = paths.has('backend/src/index.ts');

  const patched = entries.map((entry) =>
    entry.path === 'package.json' && hasFrontend ? { ...entry, contents: patchPackageJson(entry.contents) } : entry,
  );
  const added: ZipEntry[] = [];
  const add = (entry: ZipEntry): void => {
    if (!paths.has(entry.path)) added.push(entry);
  };

  if (hasFrontend) {
    add({ path: 'frontend/index.html', contents: indexHtml(title) });
    add({ path: 'vite.config.mjs', contents: VITE_CONFIG });
  }
  add({ path: 'README.md', contents: readme(title, hasBackend, hasFrontend) });
  add({ path: '.gitignore', contents: 'node_modules/\ndist/\n*.db\n' });
  return [...patched, ...added];
}

function patchPackageJson(contents: string): string {
  let manifest: Record<string, unknown>;
  try {
    manifest = JSON.parse(contents) as Record<string, unknown>;
  } catch {
    return contents;
  }
  const scripts = { ...(manifest['scripts'] as Record<string, string> | undefined) };
  scripts['web'] ??= 'vite';
  scripts['web:build'] ??= 'vite build';
  const devDependencies = { ...(manifest['devDependencies'] as Record<string, string> | undefined) };
  devDependencies['vite'] ??= VITE_VERSION;
  devDependencies['@vitejs/plugin-react'] ??= VITE_REACT_PLUGIN_VERSION;
  return `${JSON.stringify({ ...manifest, scripts, devDependencies }, null, 2)}\n`;
}

function escapeHtml(text: string): string {
  return text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

function indexHtml(title: string): string {
  return [
    '<!doctype html>',
    '<html lang="en">',
    '  <head>',
    '    <meta charset="UTF-8" />',
    '    <meta name="viewport" content="width=device-width, initial-scale=1.0" />',
    `    <title>${escapeHtml(title)}</title>`,
    '    <style>body { margin: 0; font-family: system-ui, -apple-system, "Segoe UI", sans-serif; }</style>',
    '  </head>',
    '  <body>',
    '    <div id="root"></div>',
    '    <script type="module" src="/src/main.tsx"></script>',
    '  </body>',
    '</html>',
    '',
  ].join('\n');
}

const VITE_CONFIG = [
  "import { defineConfig } from 'vite';",
  "import react from '@vitejs/plugin-react';",
  '',
  '// Serves frontend/ and forwards /api calls to the backend (npm start, port 3000).',
  'export default defineConfig({',
  "  root: 'frontend',",
  '  plugins: [react()],',
  "  server: { port: 5173, proxy: { '/api': 'http://localhost:3000' } },",
  "  build: { outDir: '../dist/web', emptyOutDir: true },",
  '});',
  '',
].join('\n');

function readme(title: string, hasBackend: boolean, hasFrontend: boolean): string {
  const lines = [`# ${title}`, '', 'Generated by Vibe-Code Blueprint.', '', '## Requirements', '', '- Node.js 22.5 or newer', '', '## Run it', '', '```bash', 'npm install', '```', ''];
  if (hasBackend) {
    lines.push('Start the API (http://localhost:3000):', '', '```bash', 'npm run build', 'npm start', '```', '');
  }
  if (hasFrontend) {
    lines.push(
      `${hasBackend ? 'In a second terminal, start' : 'Start'} the web UI (http://localhost:5173):`,
      '',
      '```bash',
      'npm run web',
      '```',
      '',
      'Build the UI for hosting with `npm run web:build` (output in `dist/web`).',
      '',
    );
  }
  return lines.join('\n');
}
