/**
 * Page sync: when a Page Builder page's form changes, bring the backend and
 * database along with it.
 *
 * The page's form (canvas-form.ts) is the contract: its fields, their kinds,
 * and the endpoint it posts to. From that, this adds - or replaces - two
 * components in the project plan:
 *
 *   - a database "<Page> Store": one SQLite table with a column per field;
 *   - a backend "<Page> API": POST / validates and stores a submission,
 *     GET / lists them - mounted at the exact path the page posts to.
 *
 * Their CODE is generated by the same component generator every other
 * component goes through (same prompts, same import rules, same export
 * contracts); only their PURPOSE is new, and it is built deterministically
 * from the field list. The caller then builds, repairs, verifies and saves
 * the result as a new run, exactly as a generation does.
 */
import {
  backendEntryPointFile,
  frontendEntryPointFile,
  packageJsonFile,
  tsconfigFile,
  type GeneratedFile,
} from './assemble.js';
import { describeFields, formFields, pageApiComponentName, pageApiPath, pageStoreComponentName, type FormField } from './canvas-form.js';
import type { PageLayout } from './canvas-layout.js';
import { createComponentCodeGenerator, type CreateComponentCodeGeneratorOptions } from './component-codegen.js';
import { generateComponentFile, schemaImpliesDatabase, type GenerateProjectFailure } from './generate-project.js';
import { componentId, type Component, type DomainName, type ProjectSchema, type ValidatedProjectSchema } from '../types/project-schema.js';
import type { Result } from '../types/result.js';
import { validateProjectSchema } from '../workflow/validate-project-schema.js';

export interface PageSyncPlan {
  readonly schema: ValidatedProjectSchema;
  readonly fields: readonly FormField[];
  readonly store: Component;
  readonly api: Component;
}

export type PageSyncPlanError =
  | { readonly reason: 'no-form-fields' }
  | { readonly reason: 'invalid-schema'; readonly message: string };

function tableName(pageName: string): string {
  const snake = pageName.trim().toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_+|_+$/g, '');
  return `${/^[a-z]/.test(snake) ? snake : `page_${snake}`}_submissions`;
}

function storePurpose(pageName: string, fields: readonly FormField[]): string {
  const hasPassword = fields.some((field) => field.kind === 'password');
  return [
    `Stores what people submit on the "${pageName}" page.`,
    `Creates (if missing) a SQLite table named ${tableName(pageName)} with an integer primary key id, a created_at timestamp, and one column per field: ${describeFields(fields)}.`,
    'Booleans are stored as 0/1 and numbers as REAL.',
    hasPassword ? 'Password fields are hashed with node:crypto scrypt and a random salt before storing - never stored in plain text.' : '',
    'Exports a function that inserts one submission and returns its new id, and a function that lists all submissions newest first.',
  ]
    .filter(Boolean)
    .join(' ');
}

function apiPurpose(pageName: string, fields: readonly FormField[]): string {
  const secret = fields.filter((field) => field.kind === 'password').map((field) => field.name);
  return [
    `HTTP API behind the "${pageName}" page's form, mounted at ${pageApiPath(pageName)}.`,
    `POST / accepts a JSON body with exactly these fields: ${describeFields(fields)}.`,
    'It validates each one (text and password must be non-empty strings, email must be a string containing @, number must be a finite number, date must be a YYYY-MM-DD string, boolean must be true or false),',
    `responds 400 with { error } naming the first invalid field, otherwise stores the submission through the "${pageStoreComponentName(pageName)}" database component and responds 201 with { id }.`,
    `GET / responds 200 with the stored submissions${secret.length > 0 ? `, never including ${secret.join(', ')}` : ''}.`,
  ].join(' ');
}

/** Replaces a same-named component (case-insensitively), or appends it. */
function upsert(components: readonly Component[], next: Component): Component[] {
  const key = next.name.toLowerCase();
  const kept = components.filter((component) => component.name.toLowerCase() !== key);
  return [...kept, next];
}

function withDependency(dependsOn: readonly DomainName[], domain: DomainName): DomainName[] {
  return dependsOn.includes(domain) ? [...dependsOn] : [...dependsOn, domain];
}

export function planPageSync(schema: ValidatedProjectSchema, layout: PageLayout): Result<PageSyncPlan, PageSyncPlanError> {
  const fields = formFields(layout);
  if (fields.length === 0) return { ok: false, error: { reason: 'no-form-fields' } };

  const component = (domain: DomainName, name: string, purpose: string): Component => ({ id: componentId(domain, name, purpose), name, purpose });
  const store = component('database', pageStoreComponentName(layout.pageName), storePurpose(layout.pageName, fields));
  const api = component('backend', pageApiComponentName(layout.pageName), apiPurpose(layout.pageName, fields));

  const candidate: ProjectSchema = {
    ...schema,
    domains: {
      ...schema.domains,
      database: { ...schema.domains.database, components: upsert(schema.domains.database.components, store) },
      backend: {
        components: upsert(schema.domains.backend.components, api),
        dependsOn: withDependency(schema.domains.backend.dependsOn, 'database'),
      },
      frontend: { ...schema.domains.frontend, dependsOn: withDependency(schema.domains.frontend.dependsOn, 'backend') },
    },
  };
  const validated = validateProjectSchema(candidate);
  if (!validated.ok) {
    return { ok: false, error: { reason: 'invalid-schema', message: validated.error.map((r) => JSON.stringify(r)).join('; ') } };
  }
  return { ok: true, value: { schema: validated.value, fields, store, api } };
}

/**
 * The run's files with the store and API generated (database first, so the
 * API is written against the store's real exports) and the templated wiring -
 * package.json, tsconfig, entry points - re-derived from the new plan.
 */
export async function generatePageSyncFiles(
  plan: PageSyncPlan,
  files: readonly GeneratedFile[],
  options: CreateComponentCodeGeneratorOptions,
): Promise<Result<readonly GeneratedFile[], GenerateProjectFailure>> {
  const generator = createComponentCodeGenerator(options);
  const { schema } = plan;
  const replace = (list: readonly GeneratedFile[], file: GeneratedFile): GeneratedFile[] => [...list.filter((f) => f.path !== file.path), file];

  let current: GeneratedFile[] = [...files];
  for (const [domain, component] of [['database', plan.store], ['backend', plan.api]] as const) {
    const generated = await generateComponentFile(generator, schema, component, domain, undefined, current);
    if (!generated.ok) return generated;
    current = replace(current, generated.value);
  }

  const hasFrontend = schema.domains.frontend.components.length > 0;
  current = replace(current, packageJsonFile({ database: schemaImpliesDatabase(schema), frontend: hasFrontend }));
  current = replace(current, tsconfigFile({ frontend: hasFrontend }));
  current = replace(current, backendEntryPointFile([...schema.domains.backend.components], [...schema.domains.security.components]));
  if (hasFrontend) current = replace(current, frontendEntryPointFile([...schema.domains.frontend.components]));
  return { ok: true, value: current };
}
